### ISSUE TITLE
s2rdf: SELECT * { ... } queries cause exception in SQL rewriting step

### ISSUE THREAD

**Issue by Aklakan** [SANSA-Stack/SANSA-Query#1]
The class [SqlOpTranslator](s2rdf-query-translator/src/main/java/queryTranslator/SqlOpTranslator.java#L75) apparently cannot handle algebra expressions which do contain a Project op
Note: Instead of trying to hack in the injections of project ops, the query translator should be enhanced to deal with such valid algebra expressions!

**Comment by Aklakan** [comment]
this is an s2rdf specific issue.

**Comment by SimonBin** [comment]
Closing for now, since we don't have immediate plans to address it
