### ISSUE TITLE
Add possibility to add Variable Mapping to the result set of Sparqlify approach

### ISSUE THREAD

**Issue by GezimSejdiu** [SANSA-Stack/SANSA-Query#13]
As the SANSA query API provides as well possibilities to write queries directly without exposing one endpoint : 
```scala
val triples = spark.rdf(input)(path)
val query = "SELECT * WHERE {?s ?p ?o} LIMIT 10"
val result = triples.sparql(triples) 
```
Here we get as a result in a [data frame of bindings](https://github.com/SANSA-Stack/SANSA-Query/blob/develop/sansa-query-spark/src/main/scala/net/sansa_stack/query/spark/sparqlify/QueryExecutionSpark.scala#L41) and would be great if we provide a wrapper which map variables to the result set.

Best

**Comment by Aklakan** [comment]
So the clear way to get the result as a table would be for sparql query execution yield essentially a (RDB2RDF) Mapping - i.e.:

* a spark dataset (conceptionally a table) with a 'natural' (by convention) representation of the values
  * Example conventions: uris become strings, RDF integers become scala integers, in the case of language tags, the column name of the value matches that of the variable, etc
* a mapping how to construct the exact correct SPARQL Bindings from the dataset - i.e. ?myVar = STRLANG(?label, ?label_lang)

**Comment by Aklakan** [comment]
Maybe we can solve this issue with a simple variable substitution: The final mapping is comprised of (a) the sql query (or its algebra expression) and the (multi) mapping of each sparql variable to a set of defining expressions:
```
?s = {uri(?foo), plainLiteral(?bar), ...}
?o = {typedLiteral(?baz, my:datatype) }
```

So by analyzing this mapping, we can decide which columns are needed, and apply a substitution on the sql expression to tidy of variable name.
Ontop seems to use nice variable names from the group up; maybe the substitution is not needed there.

**Comment by Aklakan** [comment]
Please continue discussion at #47
