### ISSUE TITLE
FILTER in Sparql cannot match int value correctly

### ISSUE THREAD

**Issue by sui414** [SANSA-Stack/SANSA-Query#14]
When I filter by int value, it returned empty list while in the result there should be some values matched. No error message.

This is my test on GraphDB, showing the query can return matched results:
![image](https://user-images.githubusercontent.com/22208403/40845854-2db6a672-65b8-11e8-9cb8-bd2ab0f788a6.png)

This is my test on SANSA: https://dbc-c63f139d-39c4.cloud.databricks.com/#notebook/522/command/531 (command 6)
![image](https://user-images.githubusercontent.com/22208403/40845902-4a4f5b4e-65b8-11e8-919b-c4141639b777.png)

**Comment by Aklakan** [comment]
The issue is, that the value is out of range of (4 byte) ints and while I see in the code that Sparqlify actually has registrations for long and decimal, this is not fully implemented and maps these mightier types back to int.

**Comment by LorenzBuehmann** [comment]
Solved by using the Ontop SPARQL engine in 0.8 release.
