### ISSUE TITLE
FILTER in Sparql cannot match string with type transformation

### ISSUE THREAD

**Issue by sui414** [SANSA-Stack/SANSA-Query#15]
when filter string in sparql, I used regex() and str() to match the substring. it worked in GraphDB as follows:

![image](https://user-images.githubusercontent.com/22208403/40846306-7ca048dc-65b9-11e8-8d0c-011e68a4d75a.png)

When I try on SANSA query layer, it gave an error:
![image](https://user-images.githubusercontent.com/22208403/40846330-9413f9f0-65b9-11e8-9326-007748eafa00.png)

The notebook is: https://dbc-c63f139d-39c4.cloud.databricks.com/#notebook/522/command/531 (command 7)

**Comment by LorenzBuehmann** [comment]
Is already covered in the Ontop-based SPARQL-to-SQL generator, so this works at least with Ontop.

**Comment by Aklakan** [comment]
Fixed an issue in the regex mapping for spark in sparqlify, so closing the issue.
However, I don't know on which source datatype the string conversion is applied to, so maybe the opener's issue requires additional work on `str(...)` overload for that datatype - in that case just reopen the issue.
