### ISSUE TITLE
GROUP BY COUNT could decide on a best match

### ISSUE THREAD

**Issue by sui414** [SANSA-Stack/SANSA-Query#16]
it seems like the group_by and count functionality gives an error:
![image](https://user-images.githubusercontent.com/22208403/40847195-004ff55e-65bc-11e8-8d68-c46b43886ad0.png)

Below is my query:
![image](https://user-images.githubusercontent.com/22208403/40847212-0a06f0fc-65bc-11e8-9548-f78de3ddfe67.png)

Notebook: https://dbc-c63f139d-39c4.cloud.databricks.com/#notebook/522/command/532 (command 8)

**Comment by LorenzBuehmann** [comment]
Started integration of Ontop v4 which supports aggregation so it should be fixed once Ontop will make a release.

**Comment by JensLehmann** [comment]
We need to postpone to the next SANSA release as we depend on a version 4 release of Ontop.

**Comment by Aklakan** [comment]
Aggregate functions are not supported by Sparqlify and are unlikely to ever be as this is a lot of work already having been done / being done in Ontop. In case of related problems with the future Ontop integration - once it is available - open a new issue.
