### ISSUE TITLE
STRAFTER doesn't work in sparql query

### ISSUE THREAD

**Issue by sui414** [SANSA-Stack/SANSA-Query#17]
When I try to split and select substring, I use STRAFTER in query select. Here is how it works:

![image](https://user-images.githubusercontent.com/22208403/40985771-199d5570-68e5-11e8-97c5-f82948fee083.png)

When I try it with SANSA query, it returns the same result as without any split&substring operation.
![image](https://user-images.githubusercontent.com/22208403/40985849-3736cb20-68e5-11e8-9fe1-7f3bc2555b2d.png)

The code is in notebook: https://dbc-c63f139d-39c4.cloud.databricks.com/#notebook/522/command/547 (command 9)

**Comment by GezimSejdiu** [comment]
Hi @sui414 ,
we are working towards integrating [SANSA with Ontop](https://github.com/SANSA-Stack/SANSA-Query/blob/develop/sansa-query-spark/src/main/scala/net/sansa_stack/query/spark/package.scala#L84,L94), and we have implemented a very first version of it. We will provide more tests and see if this SPARQL feature is already supported within this integration than we will let you know to give it a try.

Best

**Comment by Aklakan** [comment]
Fixed, verified with test cases.
