### ISSUE TITLE
Compare / Evaluate further RDB2RDF tools

### ISSUE THREAD

**Issue by patrickwestphal** [SANSA-Stack/SANSA-Query#19]

**Comment by patrickwestphal** [comment]
- [ ] Ontop
- [ ] Morph-rdb
- [ ] Sparqlmap
- [ ] Exporting table and index building instructions
- [ ] Exporting R2RML mappings

**Comment by JensLehmann** [comment]
We integrated Sparklify and Ontop. If there is demand for further RDB2RDF rewriters, separate issues should be opened.
