### ISSUE TITLE
Integrate SPARQL Test Suite

### ISSUE THREAD

**Issue by patrickwestphal** [SANSA-Stack/SANSA-Query#20]
E.g. https://www.w3.org/2009/sparql/docs/tests/summary.html or something newer

**Comment by LorenzBuehmann** [comment]
SPARQL 1.0 and SPARQL 1.1 test suite will be merged with Ontop v4 integration soon.

**Comment by akuckartz** [comment]
Why is this issue closed before it is resolved?

**Comment by LorenzBuehmann** [comment]
Because it's not an issue at all but just providing access to a test suite - at least in my opinion it's not worth to be a Github issue.
Anyways, I'll reopen it and mark it as resolved next week once the code has been pushed to Github repo.

**Comment by LorenzBuehmann** [comment]
Test cases are now part of a separate Maven module.

It contains a test suite as well as a [test suite runner stub](https://github.com/SANSA-Stack/SANSA-Query/blob/develop/sansa-query-tests/src/main/scala/net/sansa_stack/query/tests/SPARQLQueryEvaluationTestSuiteRunner.scala) which has to be implemented.


Small documentation will be added soon as well as a Spark based implementation for Ontop.
