### ISSUE TITLE
"null" values in Query result format

### ISSUE THREAD

**Issue by purohitsumit** [SANSA-Stack/SANSA-Query#43]
Hi 

SANSA-Query returns strange "null" values in addition to the expected variables. 
For the attached sample file (extension is changed as .ttl is not allowed) and for the simple query 
`
"SELECT ?o WHERE {?s ?p ?o} "
`
[test2.ttl.txt](https://github.com/SANSA-Stack/SANSA-Query/files/3884456/test2.ttl.txt)

I get following ?o
`[Alice,,null]
[Bob,,null]
[Clare,,null]
[null,null,c922def1e6fa0a4aec50621290367fd1]
[null,null,94f03f04f0cef66952474449e02a1942]
[CT,,null]
`

Is there an issue with variable binding ?

Thanks

**Comment by GezimSejdiu** [comment]
Hi @purohitsumit ,
many thanks for the issue. Indeed, this is related to the variable binding as described on issue #13 and the `null` values are because of the result set containing all the schema (including RDF terms).

We will try to resolve this issue as soon as possible and map the bindings to the variables present in the projection clause.

Best regards,

**Comment by Aklakan** [comment]
This is actually a design issue of .sparql() that it exposes the raw SQL result set - without the mapping that creates the actual bindings having been applied. So NULL values are valid at this stage.
An RDF terms in general need to be represented with multiple SQL columns if only using the standard SQL datatypes (RDFTerm is typically NOT supported by SQL)
For example: If in SPARQL there are two bindings with a string and an int value for ?x, in the SQL result set there will conceptually be an x_int and an x_string column. The two rows will have one column holding the value and the other one set to NULL.

Note: Improving the naming of columns is subject of #13.

**Comment by Aklakan** [comment]
@GezimSejdiu @dgraux This is an API design issue and we discussed some time ago, that we will face the same issue with ontop - i.e. any sparql-to-sql rewrite has at least two parts: the SQL result table and the mapping to SPARQL bindings.
I see the following options that .sparql() return for SELECT queries:

* Some subclass of DataFrame, where the DataFrame is the raw SQL result (as it is now) plus extra methods to create bindings - this way we not break any existing code relying on .sparql - however, using the DataFrame of `.sparql()` would then be highly dependent on the OBDA engine, which seems awkward for such a central function
* Let .sparql() return some intermediate object from which one can obtain the bindings or the raw DataFrame
* Introduce a sibling method of .sparql() that returns a more meaningful result

**Comment by Aklakan** [comment]
Please continue discussion at #47
