### ISSUE TITLE
No results for query that matches blank node

### ISSUE THREAD

**Issue by purohitsumit** [SANSA-Stack/SANSA-Query#44]
Hi SANSA-Query team,

SANSA-Query does not return any result if it matches a blank node. 
Using following query 
`
"""
               prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
               SELECT ?stm ?en ?enAtr ?enAtrVal
       WHERE {
          ?stm rdf:subject ?en .
          ?stm rdf:predicate ?enAtr .
          ?stm rdf:object ?enAtrVal .
       }
       """
`

[test2.ttl](https://github.com/SANSA-Stack/SANSA-Query/files/3893437/test2.ttl.txt)
 returns expected results. But 
[test.ttl](https://github.com/SANSA-Stack/SANSA-Query/files/3893439/test.ttl.txt)  does not show ANY result, not even the non-blank node result.  I also see that in the blank node case, it also outputs lots of debug statement such as 
`
CAST TO string
CAST TO string
CAST TO string
CAST TO string
CAST TO string
CAST TO string
CAST TO string
CAST TO string
CAST TO string
CAST TO string
CAST TO string
`
I do set the valid language as 
`
val lang = Lang.TURTLE
`

I see the same behavior for ".nt" format.  Please suggest me what is causing this issue and if there is a way to fix it. 

Thanks
Sumit

**Comment by Aklakan** [comment]
Fixed in SparqlifyUtils2.java in RDF layer; the reason was a name clash: triples with IRIs and bnodes are managed in separate tables but the same name was generated for their tables.
Added this issue as a test case to the query layer.

**Comment by dileepvikram** [comment]
Hello Aklakan,
                 Is this issue fixed and available to use now ?
