### ISSUE TITLE
I got error every time  I try to load large ttl file

### ISSUE THREAD

**Issue by AlberTadrous** [SANSA-Stack/SANSA-Query#49]
I got "org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 28.0 failed 4 times, most recent failure: Lost task 0.3 in stage 28.0 (TID 43, 10.3.1.9, executor 20): java.lang.OutOfMemoryError: Requested array size exceeds VM limit" everytime I load large ttl "450MB".

Do you know why?

**Comment by LorenzBuehmann** [comment]
can you provide more details about your Spark setup? Which version of SANSA do you submit how and what query do you try? Also, the format is Turtle?

**Comment by JensLehmann** [comment]
Please double-check whether the issue still persists in the current develop branch.

**Comment by LorenzBuehmann** [comment]
This should have been resolved with the new RDF loader in the RDF layer. If the issue does still occur on your end, feel free to comment here and I will re-open the issue and investigate further, ideally with more details on the setup.
